from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import VendorViewSet, ProductViewSet, OrderViewSet, RegisterView, CustomLoginView, CustomLogoutView

router = DefaultRouter()
router.register(r'vendors', VendorViewSet, basename='vendor')
router.register(r'products', ProductViewSet, basename='product')
router.register(r'orders', OrderViewSet, basename='order')

urlpatterns = [
    # Custom registration, login, and logout
    path('register/', RegisterView.as_view(), name='register'),  # Custom register
    path('login/', CustomLoginView.as_view(), name='custom_login'),  # Custom login
    path('logout/', CustomLogoutView.as_view(), name='custom_logout'),  # Custom logout

    # Include all ViewSet routes generated by the router
    path('', include(router.urls)),

    # API authentication (for browsable API login)
    path('api-auth/', include('rest_framework.urls')),
]
